using LillysCatering.Models;
using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore;

namespace LillysCatering.Data;

public class ApplicationDbContext : IdentityDbContext
{
    public ApplicationDbContext(DbContextOptions<ApplicationDbContext> options)
        : base(options)
    {
    }

    // Database tables generated by using models
    public DbSet<Menu> Menus { get; set; }

    public DbSet<Dish> Dishes { get; set; }

    public DbSet<Booking> Bookings { get; set; }
}

